### ISSUE TITLE
Привет

### ISSUE THREAD

**Issue by KarimullinArthur** [YariKartoshe4ka/Space-Way#15]
Привет, извени, что пишу тут, не нашёл на твоём гитхабе, как сязаться с тобой, хочу принять участие в разработке, хотя я с пай гейм ни разу не работал, ну хочу попробовать по контребьютить в чужие репы :)

**Comment by YariKartoshe4ka** [comment]
Привет! В данный момент я работаю над релизом [2.3.0](https://github.com/YariKartoshe4ka/Space-Way/milestone/4). Я хотел бы посвятить его обновлению спрайтов и оптимизации кода, и, возможно, если мне предоставиться возможность получить VPS, то и глобальную таблицу рекордов, поэтому:

- Если ты художник, то можешь поработать со спрайтами. Более подробное ТЗ тут #14 
- Если ты хочешь поработать с кодом, то из задач есть только оптимизация:
    - Можешь вычислить слабые места и предложить/исправить их (cProfile в помощь). Особенно актуально для Android
    - Если у тебя Mac OS, то было бы круто, если бы ты изменил setup.py чтоб он устанавливал ярлык (как для linux)
    - Переписать hitbox.py на Cython

Всегда открыт для PR
Связаться можно в [тг](https://t.me/yarikartoshe4ka)
